HMA-9215 fixed Double.shouldApplyDefaultTaxCode() extension function to compare with default tax code.
hmrc/tax-kalculator pull request #130
Opened 2024-10-30 09:53 UTC by annadahmrc

ticket :- https://jira.tools.tax.service.gov.uk/browse/HMA-9215

Fixed the Double.shouldApplyDefaultTaxCode(): - change the condition from the standardTaxCode to default-tax-code
<img width="292" alt="Screenshot 2024-10-30 at 09 52 45" src="https://github.com/user-attachments/assets/b803ca39-2cd8-4499-b2ef-fa1f7e536ead">

2024-10-30 12:06 UTC, ngoulongkam requested changes
Also you have forgotten to update the CHANGELOG.

2024-10-30 12:06 UTC, ngoulongkam commented on src/commonMain/kotlin/uk/gov/hmrc/calculator/utils/tapering/TaperingExtensions.kt
> +        yearlyWageAfterPension.yearlyWageIsAboveHundredThousand()
This is great, but instead of adding this as an additional function, it should completely replace the usage of `isStandardTaxCodeAndAboveHundredThousand` because checking against `StandardTaxCode` was the wrong thing to do.

2024-10-31 08:44 UTC, annadahmrc commented
> Also you have forgotten to update the CHANGELOG.

@ngoulongkam updated changelog

2024-10-31 08:44 UTC, annadahmrc commented on src/commonMain/kotlin/uk/gov/hmrc/calculator/utils/tapering/TaperingExtensions.kt
> +        yearlyWageAfterPension.yearlyWageIsAboveHundredThousand()
@ngoulongkam updated with:-
`@JvmSynthetic
internal fun Double.shouldApplyDefaultTaxCode(taxCode: String, userSuppliedTaxCode: Boolean) =
    taxCode.endsWith(TaxCode.getDefaultTaxCode(), ignoreCase = true) &&
        this.yearlyWageIsAboveHundredThousand() &&
        userSuppliedTaxCode`

2024-10-31 11:52 UTC, ngoulongkam requested changes

2024-10-31 11:52 UTC, ngoulongkam commented on src/commonMain/kotlin/uk/gov/hmrc/calculator/utils/tapering/TaperingExtensions.kt
> +        userSuppliedTaxCode
I'm sorry I think you misunderstood my last comment. 

what I meant is that the logic of `taxCode.endsWith` should replace the logic inside the `isStandardTaxCodeAndAboveHundredThousand()` function. 

so the `isStandardTaxCodeAndAboveHundredThousand` should look something like this:
```
private fun isStandardTaxCodeAndAboveHundredThousand(taxCode: String, yearlyWageAfterPension: Double) =
    taxCode.endsWith(TaxCode.getDefaultTaxCode(), ignoreCase = true) && yearlyWageAfterPension.yearlyWageIsAboveHundredThousand()
```

After this, the `shouldApplyStandardTapering` and `shouldApplyDefaultTaxCode` should just be passing a Sting `taxCode` instead of `taxCodeType`.

2024-10-31 12:29 UTC, ngoulongkam approved these changes

2024-11-04 17:12 UTC, merged