HMA-7089: Added Pension Contribution
hmrc/tax-kalculator pull request #80
Opened 2023-07-07 10:25 UTC by ngoulongkam

2023-07-10 10:02 UTC, chrisob55 requested changes
It'd be great if we could also include the pension contributions in the [integration tests](https://github.com/hmrc/tax-kalculator/blob/main/src/jvmTest/kotlin/uk/gov/hmrc/calculator/ParameterizedCalculatorTests.kt). That way, we have very thorough tests.

2023-07-10 12:50 UTC, ngoulongkam commented
@chrisob55 This PR is 1 of the 3 parts (Pension/Tapering/Student Loan).

Reason why I haven't added any integration test is because we still need the business to get back to us with some "validated" test data. 

This will probably come as part of the whole shebang with the last PR when all 3 parts are done.

2023-07-10 12:51 UTC, chrisob55 commented
> @chrisob55 This PR is 1 of the 3 parts (Pension/Tapering/Student Loan).
> 
> Reason why I haven't added any integration test is because we still need the business to get back to us with some "validated" test data.
> 
> This will probably come as part of the whole shebang with the last PR when all 3 parts are done.

Cool

2023-07-12 11:30 UTC, ngoulongkam commented on src/commonMain/kotlin/uk/gov/hmrc/calculator/model/pension/AnnualPensionMethod.kt
> +    PERCENTAGE, AMOUNT_IN_POUND
Address in [7644499](https://github.com/hmrc/tax-kalculator/pull/80/commits/7644499ccc5cc0f3eef75a60a294d30f99d5a51d)

Marking as resolved.

2023-11-20 11:53 UTC, jemmaSlater approved these changes

2023-11-21 09:19 UTC, merged